apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: o4v82yr7o-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:3e16edfc7f7fe9a0d9d9fc791899a7ef05689224@sha256:98326a724cc8663571b42385a24c84c05163f6a5f6691c742046b75746c985d8
          name: container-image
